version: '3.8'

services:
  mysqldb:
    image: mysql:latest  
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
      
    ports:
      - "3306:3306"
    volumes:
      - mysqlvol:/var/lib/mysql

  springbootapp:
    image: haithamomh/springk8s:1.1.0  
    container_name: springbootapp
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/testdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      spring.datasource.password: 123456
   
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb

  angularapp:
    image: haithamomh/angularapp:latest  
    container_name: angularapp
    ports:
      - "80:80"
    depends_on:
      - springbootapp

volumes:
  mysqlvol:
